### ISSUE TITLE
m4b-tool docker image - inspired by your work

### ISSUE THREAD

**Issue by sandreas** [kmlucy/docker-m4b-tool#1]
Hey there,

i really appreciate your work and would like to thank you for providing a docker image for `m4b-tool`. 

Inspired by your work, i created an experimental dockerfile including the best quality encoders and would like to ask you, if you could check it out and provide feedback.

See https://github.com/sandreas/m4b-tool#docker-experimental for details.

Thank you!

sandreas

**Comment by kmlucy** [comment]
@sandreas It works well for me. My main concern was the size of the image, but even though it's large at 638MB, it's certainly not unreasonable. 

I have two suggestions to improve it. One is to set the `WORKDIR` in the Dockerfile so you don't have to do it at runtime. The other is to set your `ENTRYPOINT` to `m4b-tool` and your command to `"--help"`. That's how I did it in my version, and that would let you clean up your alias to the below, and if people run it without a command, it will default to `--help`.

```
alias m4b-tool='docker run -it --rm -u $(id -u):$(id -g) -v "$(pwd)":/mnt m4b-tool'
```

**Comment by sandreas** [comment]
Ok, sounds reasonable. Thank you very much for your feedback, I'm working on it.

**Comment by kmlucy** [comment]
Sure, let me know if you have any other questions.
