### ISSUE TITLE
Your ffmpeg version cannot produce top quality aac using encoder aac instead of libfdk_aac

### ISSUE THREAD

**Issue by amlucent** [kmlucy/docker-m4b-tool#2]
I guess this is just a non urgent feature request. I am using this container and it is working very well but I keep seeing this error.  I thought maybe you would update the deployment to include this libfdk_aac.  Thanks.

> Your ffmpeg version cannot produce top quality aac using encoder aac instead of libfdk_aac

**Comment by kmlucy** [comment]
That would require compiling ffmpeg with fdkaac, which I don't want to do in this image, but I believe the official Dockerfile includes it: https://github.com/sandreas/m4b-tool/blob/master/README.md#docker
